apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-starter-deployment
  labels:
    name: k8-starter-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8-starter-label
  template:
    metadata:
      labels:
        name: k8-starter-label
    spec:
      containers:
        - name: k8-starter
          image: starter:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090