kind: Service
apiVersion: v1
metadata:
  name: k8-starter-service
spec:
  selector:
    name: k8-starter-label
  type: NodePort
  ports:
    - name: http
      port: 81
      targetPort: 8090
      protocol: TCP